jobs:
  - job: test
    steps: 
      - task: Npm@1
        displayName: install
        inputs:
         command: 'install'
         workingDir: 'create-react-app'

      - task: Npm@1
        displayName: Build
        inputs:
          command: 'custom'
          workingDir: 'create-react-app'
          customCommand: 'run build'

      - task: PublishPipelineArtifact@1
        inputs:
         targetPath: '$(Build.ArtifactStagingDirectory)/React-JS-Sample-Code'
         artifact: 'drop'
         publishLocation: 'pipeline'
